/* 
 * Copyright (C) 2014 David Barry <david.barry at cancer.org.uk>
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */
package ui;

import Adapt.Analyse_Movie;
import Adapt.StaticVariables;
import Adapt.UserVariables;
import ij.IJ;
import ij.ImagePlus;
import ij.ImageStack;
import ij.gui.ImageCanvas;
import ij.process.AutoThresholder;
import ij.process.ByteProcessor;
import ij.process.ColorProcessor;
import ij.process.ImageProcessor;
import ij.process.TypeConverter;
import java.awt.Dimension;
import java.awt.Toolkit;
import javax.swing.DefaultBoundedRangeModel;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JLabel;
import javax.swing.JTextField;
import javax.swing.JToggleButton;

/**
 *
 * @author barry05
 */
public class GUI extends javax.swing.JDialog {

    private Analyse_Movie analyser;
    private ImagePlus cytoImp, sigImp;
    private ImageProcessor cytoProc, sigProc;
    private ImageStack[] stacks;
    private String title;
    private boolean wasOKed = false;
    private final int MAX_DIM = 512;

    /**
     * Creates new form GUI
     */
    public GUI(java.awt.Frame parent, boolean modal, String title, ImageStack[] stacks, Analyse_Movie analyser) {
        super(parent, modal);
        this.stacks = stacks;
        this.title = title;
        this.analyser = analyser;
        cytoProc = stacks[0].getProcessor(1).duplicate();
        cytoProc = checkImageDimensions(cytoProc);
        cytoImp = new ImagePlus("", cytoProc);
        if (stacks[1] != null) {
            sigProc = stacks[1].getProcessor(1).duplicate();
            sigProc = checkImageDimensions(sigProc);
            sigImp = new ImagePlus("", sigProc);
        } else {
            sigImp = new ImagePlus("", new ByteProcessor(cytoProc.getWidth(), cytoProc.getHeight()));
        }
        initComponents();
        Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
        this.setLocation(dim.width / 2 - this.getWidth() / 2, dim.height / 2 - this.getHeight() / 2);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel2 = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        simpleTab = new javax.swing.JPanel();
        greyThreshLabel = new javax.swing.JLabel();
        greyThreshField = new javax.swing.JTextField();
        spatResLabel = new javax.swing.JLabel();
        spatResField = new javax.swing.JTextField();
        timeResLabel = new javax.swing.JLabel();
        timeResField = new javax.swing.JTextField();
        gaussRadLabel = new javax.swing.JLabel();
        gaussRadField = new javax.swing.JTextField();
        autoThreshToggleButton = new javax.swing.JToggleButton();
        genVisToggleButton = new javax.swing.JToggleButton();
        genMorphToggleButton = new javax.swing.JToggleButton();
        cortexDepthField = new javax.swing.JTextField();
        cortexDepthLabel = new javax.swing.JLabel();
        minTrajLabel = new javax.swing.JLabel();
        minTrajTextField = new javax.swing.JTextField();
        advancedTab = new javax.swing.JPanel();
        erosionField = new javax.swing.JTextField();
        erosionLabel = new javax.swing.JLabel();
        spatFiltRadLabel = new javax.swing.JLabel();
        spatFiltRadField = new javax.swing.JTextField();
        tempFiltRadLabel = new javax.swing.JLabel();
        tempFiltRadField = new javax.swing.JTextField();
        simpSegRadioButton = new javax.swing.JRadioButton();
        advSegRadioButton = new javax.swing.JRadioButton();
        initFiltRadLabel = new javax.swing.JLabel();
        initFiltRadTextField = new javax.swing.JTextField();
        lambdaLabel = new javax.swing.JLabel();
        lambdaTextField = new javax.swing.JTextField();
        threshComboBox = new javax.swing.JComboBox();
        threshLabel = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        minCurveRangeLabel = new javax.swing.JLabel();
        minCurveRangeField = new javax.swing.JTextField();
        minCurveThreshLabel = new javax.swing.JLabel();
        minCurveThreshField = new javax.swing.JTextField();
        cutOffLabel = new javax.swing.JLabel();
        cutOffField = new javax.swing.JTextField();
        sigThreshFactLabel = new javax.swing.JLabel();
        sigThreshFactField = new javax.swing.JTextField();
        sigRecThreshLabel = new javax.swing.JLabel();
        sigRecThreshField = new javax.swing.JTextField();
        anaProtToggleButton = new javax.swing.JToggleButton();
        useSigThreshToggleButton = new javax.swing.JToggleButton();
        maxCurveRangeField = new javax.swing.JTextField();
        maxCurveThreshField = new javax.swing.JTextField();
        maxCurveRangeLabel = new javax.swing.JLabel();
        maxCurveThreshLabel = new javax.swing.JLabel();
        velDetectRadioButton = new javax.swing.JRadioButton();
        curveDetectRadioButton = new javax.swing.JRadioButton();
        protLenLabel = new javax.swing.JLabel();
        protDurLabel = new javax.swing.JLabel();
        protLenTextField = new javax.swing.JTextField();
        protDurTextField = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        cytoCanvas = new ImageCanvas(cytoImp);
        previewToggleButton = new javax.swing.JToggleButton();
        previewField = new javax.swing.JTextField();
        cytoLabel = new javax.swing.JLabel();
        sigCanvas = new ImageCanvas(sigImp);
        sigLabel = new javax.swing.JLabel();
        previewScrollBar = new javax.swing.JScrollBar();
        jPanel5 = new javax.swing.JPanel();
        runButton = new javax.swing.JButton();
        cancelButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle(title);
        getContentPane().setLayout(new java.awt.GridBagLayout());

        jPanel2.setLayout(new java.awt.GridBagLayout());

        jTabbedPane1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        simpleTab.setLayout(new java.awt.GridBagLayout());

        greyThreshLabel.setText(StaticVariables.GREY_SENS);
        greyThreshLabel.setEnabled(!UserVariables.isAutoThreshold());
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 10, 0, 0);
        simpleTab.add(greyThreshLabel, gridBagConstraints);

        greyThreshField.setText(String.valueOf(UserVariables.getGreyThresh()));
        greyThreshField.setEnabled(!UserVariables.isAutoThreshold());
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 10);
        simpleTab.add(greyThreshField, gridBagConstraints);

        spatResLabel.setText(StaticVariables.SPAT_RES);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 10, 0, 0);
        simpleTab.add(spatResLabel, gridBagConstraints);

        spatResField.setText(String.valueOf(UserVariables.getSpatialRes()));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 10);
        simpleTab.add(spatResField, gridBagConstraints);

        timeResLabel.setText(StaticVariables.TIME_RES);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 10, 0, 0);
        simpleTab.add(timeResLabel, gridBagConstraints);

        timeResField.setText(String.valueOf(UserVariables.getTimeRes()));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 10);
        simpleTab.add(timeResField, gridBagConstraints);

        gaussRadLabel.setText(StaticVariables.GAUSS_RAD);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 10, 0, 0);
        simpleTab.add(gaussRadLabel, gridBagConstraints);

        gaussRadField.setText(String.valueOf(UserVariables.getGaussRad()));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 10);
        simpleTab.add(gaussRadField, gridBagConstraints);

        autoThreshToggleButton.setText(StaticVariables.AUTO_THRESH);
        autoThreshToggleButton.setSelected(UserVariables.isAutoThreshold());
        autoThreshToggleButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                autoThreshToggleButtonActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        simpleTab.add(autoThreshToggleButton, gridBagConstraints);

        genVisToggleButton.setText(StaticVariables.GEN_VIS);
        genVisToggleButton.setSelected(UserVariables.isGenVis());
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        simpleTab.add(genVisToggleButton, gridBagConstraints);

        genMorphToggleButton.setText(StaticVariables.GET_MORPH);
        genMorphToggleButton.setSelected(UserVariables.isGetMorph());
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        simpleTab.add(genMorphToggleButton, gridBagConstraints);

        cortexDepthField.setText(String.valueOf(UserVariables.getCortexDepth()));
        cortexDepthField.setEnabled(stacks[1]!=null);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 10);
        simpleTab.add(cortexDepthField, gridBagConstraints);

        cortexDepthLabel.setText(StaticVariables.CORTEX_DEPTH);
        cortexDepthLabel.setEnabled(stacks[1]!=null);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 10, 0, 0);
        simpleTab.add(cortexDepthLabel, gridBagConstraints);

        minTrajLabel.setText(StaticVariables.MIN_TRAJ_LENGTH);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 10, 0, 0);
        simpleTab.add(minTrajLabel, gridBagConstraints);

        minTrajTextField.setText(String.valueOf(UserVariables.getMinLength()));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 10);
        simpleTab.add(minTrajTextField, gridBagConstraints);

        jTabbedPane1.addTab("Simple", simpleTab);

        advancedTab.setLayout(new java.awt.GridBagLayout());

        erosionField.setText(String.valueOf(UserVariables.getErosion()));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 10);
        advancedTab.add(erosionField, gridBagConstraints);

        erosionLabel.setText(StaticVariables.EROSION);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 10, 0, 0);
        advancedTab.add(erosionLabel, gridBagConstraints);

        spatFiltRadLabel.setText(StaticVariables.SPAT_FILT_RAD);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 10, 0, 0);
        advancedTab.add(spatFiltRadLabel, gridBagConstraints);

        spatFiltRadField.setText(String.valueOf(UserVariables.getSpatFiltRad()));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 10);
        advancedTab.add(spatFiltRadField, gridBagConstraints);

        tempFiltRadLabel.setText(StaticVariables.TEMP_FILT_RAD);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 10, 0, 0);
        advancedTab.add(tempFiltRadLabel, gridBagConstraints);

        tempFiltRadField.setText(String.valueOf(UserVariables.getTempFiltRad()));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 10);
        advancedTab.add(tempFiltRadField, gridBagConstraints);

        simpSegRadioButton.setText(StaticVariables.SIMP_SEG);
        simpSegRadioButton.setSelected(UserVariables.isSimple());
        simpSegRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                simpSegRadioButtonActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 0);
        advancedTab.add(simpSegRadioButton, gridBagConstraints);

        advSegRadioButton.setText(StaticVariables.ADV_SEG);
        advSegRadioButton.setSelected(!UserVariables.isSimple());
        advSegRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                advSegRadioButtonActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(10, 0, 10, 10);
        advancedTab.add(advSegRadioButton, gridBagConstraints);

        initFiltRadLabel.setText(StaticVariables.INIT_FILT_RAD);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 10, 0, 0);
        advancedTab.add(initFiltRadLabel, gridBagConstraints);

        initFiltRadTextField.setText(String.valueOf(UserVariables.getInitGaussRad()));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 10);
        advancedTab.add(initFiltRadTextField, gridBagConstraints);

        lambdaLabel.setText(StaticVariables.LAMBDA);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 10, 0, 0);
        advancedTab.add(lambdaLabel, gridBagConstraints);

        lambdaTextField.setText(String.valueOf(UserVariables.getLambda()));
        lambdaTextField.setEnabled(advSegRadioButton.isSelected());
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 10);
        advancedTab.add(lambdaTextField, gridBagConstraints);

        threshComboBox.setModel(new DefaultComboBoxModel(AutoThresholder.Method.values()));
        threshComboBox.setSelectedItem(AutoThresholder.Method.valueOf(UserVariables.getThreshMethod()));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 10);
        advancedTab.add(threshComboBox, gridBagConstraints);

        threshLabel.setText(StaticVariables.THRESH_METHOD);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 10, 0, 0);
        advancedTab.add(threshLabel, gridBagConstraints);

        jTabbedPane1.addTab("Advanced", advancedTab);

        jPanel4.setLayout(new java.awt.GridBagLayout());

        minCurveRangeLabel.setText(StaticVariables.MIN_CURVE_RANGE);
        minCurveRangeLabel.setEnabled(UserVariables.isAnalyseProtrusions());
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 10, 0, 0);
        jPanel4.add(minCurveRangeLabel, gridBagConstraints);

        minCurveRangeField.setText(String.valueOf(UserVariables.getMinCurveRange()));
        minCurveRangeField.setEnabled(UserVariables.isAnalyseProtrusions());
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 10);
        jPanel4.add(minCurveRangeField, gridBagConstraints);

        minCurveThreshLabel.setText(StaticVariables.MIN_CURVE_THRESH);
        minCurveThreshLabel.setEnabled(UserVariables.isAnalyseProtrusions());
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 10, 0, 0);
        jPanel4.add(minCurveThreshLabel, gridBagConstraints);

        minCurveThreshField.setText(String.valueOf(UserVariables.getMinCurveThresh()));
        minCurveThreshField.setEnabled(UserVariables.isAnalyseProtrusions());
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 10);
        jPanel4.add(minCurveThreshField, gridBagConstraints);

        cutOffLabel.setText(StaticVariables.CUT_OFF);
        cutOffLabel.setEnabled(UserVariables.isAnalyseProtrusions());
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 10, 0, 0);
        jPanel4.add(cutOffLabel, gridBagConstraints);

        cutOffField.setText(String.valueOf(UserVariables.getCutOffTime()));
        cutOffField.setEnabled(UserVariables.isAnalyseProtrusions());
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 10);
        jPanel4.add(cutOffField, gridBagConstraints);

        sigThreshFactLabel.setText(StaticVariables.SIG_THRESH_FACT);
        sigThreshFactLabel.setEnabled(UserVariables.isAnalyseProtrusions() && UserVariables.isUseSigThresh());
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 10;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 10, 0, 0);
        jPanel4.add(sigThreshFactLabel, gridBagConstraints);

        sigThreshFactField.setText(String.valueOf(UserVariables.getSigThreshFact()));
        sigThreshFactField.setEnabled(UserVariables.isAnalyseProtrusions() && UserVariables.isUseSigThresh());
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 10;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 10);
        jPanel4.add(sigThreshFactField, gridBagConstraints);

        sigRecThreshLabel.setText(StaticVariables.SIG_REC_THRESH);
        sigRecThreshLabel.setEnabled(UserVariables.isAnalyseProtrusions() && UserVariables.isUseSigThresh());
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 11;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 10, 0, 0);
        jPanel4.add(sigRecThreshLabel, gridBagConstraints);

        sigRecThreshField.setText(String.valueOf(UserVariables.getSigRecoveryThresh()));
        sigRecThreshField.setEnabled(UserVariables.isAnalyseProtrusions() && UserVariables.isUseSigThresh());
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 11;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 10);
        jPanel4.add(sigRecThreshField, gridBagConstraints);

        anaProtToggleButton.setText(StaticVariables.ANA_PROT);
        anaProtToggleButton.setSelected(UserVariables.isAnalyseProtrusions());
        anaProtToggleButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                anaProtToggleButtonActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        jPanel4.add(anaProtToggleButton, gridBagConstraints);

        useSigThreshToggleButton.setText(StaticVariables.USE_SIG_THRESH);
        useSigThreshToggleButton.setSelected(UserVariables.isUseSigThresh());
        useSigThreshToggleButton.setEnabled(UserVariables.isAnalyseProtrusions());
        useSigThreshToggleButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                useSigThreshToggleButtonActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 9;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        jPanel4.add(useSigThreshToggleButton, gridBagConstraints);

        maxCurveRangeField.setText(String.valueOf(UserVariables.getMaxCurveRange()));
        maxCurveRangeField.setEnabled(UserVariables.isAnalyseProtrusions());
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 10);
        jPanel4.add(maxCurveRangeField, gridBagConstraints);

        maxCurveThreshField.setText(String.valueOf(UserVariables.getMaxCurveThresh()));
        maxCurveThreshField.setEnabled(UserVariables.isAnalyseProtrusions());
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 10);
        jPanel4.add(maxCurveThreshField, gridBagConstraints);

        maxCurveRangeLabel.setText(StaticVariables.MAX_CURVE_RANGE);
        maxCurveRangeLabel.setEnabled(UserVariables.isAnalyseProtrusions());
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 10, 0, 0);
        jPanel4.add(maxCurveRangeLabel, gridBagConstraints);

        maxCurveThreshLabel.setText(StaticVariables.MAX_CURVE_THRESH);
        maxCurveThreshLabel.setEnabled(UserVariables.isAnalyseProtrusions());
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 10, 0, 0);
        jPanel4.add(maxCurveThreshLabel, gridBagConstraints);

        velDetectRadioButton.setText(StaticVariables.VEL_DETECT);
        velDetectRadioButton.setSelected(UserVariables.isVelDetect());
        velDetectRadioButton.setEnabled(UserVariables.isAnalyseProtrusions());
        velDetectRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                velDetectRadioButtonActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 0);
        jPanel4.add(velDetectRadioButton, gridBagConstraints);

        curveDetectRadioButton.setText(StaticVariables.CURVE_DETECT);
        curveDetectRadioButton.setSelected(!UserVariables.isVelDetect());
        curveDetectRadioButton.setEnabled(UserVariables.isAnalyseProtrusions());
        curveDetectRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                curveDetectRadioButtonActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(10, 0, 10, 10);
        jPanel4.add(curveDetectRadioButton, gridBagConstraints);

        protLenLabel.setText(StaticVariables.PROT_LEN_THRESH);
        protLenLabel.setEnabled(UserVariables.isAnalyseProtrusions());
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 10, 0, 0);
        jPanel4.add(protLenLabel, gridBagConstraints);

        protDurLabel.setText(StaticVariables.PROT_DUR_THRESH);
        protDurLabel.setEnabled(UserVariables.isAnalyseProtrusions());
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 10, 0, 0);
        jPanel4.add(protDurLabel, gridBagConstraints);

        protLenTextField.setText(String.valueOf(UserVariables.getBlebLenThresh()));
        protLenTextField.setEnabled(UserVariables.isAnalyseProtrusions());
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 10);
        jPanel4.add(protLenTextField, gridBagConstraints);

        protDurTextField.setText(String.valueOf(UserVariables.getBlebDurThresh()));
        protDurTextField.setEnabled(UserVariables.isAnalyseProtrusions());
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 10);
        jPanel4.add(protDurTextField, gridBagConstraints);

        jTabbedPane1.addTab("Protrusion Analysis", jPanel4);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.2;
        gridBagConstraints.weighty = 1.0;
        jPanel2.add(jTabbedPane1, gridBagConstraints);

        jPanel3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel3.setLayout(new java.awt.GridBagLayout());

        cytoCanvas.setPreferredSize(new java.awt.Dimension(256, 256));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        jPanel3.add(cytoCanvas, gridBagConstraints);

        previewToggleButton.setText("Preview");
        previewToggleButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                previewToggleButtonActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        jPanel3.add(previewToggleButton, gridBagConstraints);

        previewField.setText(String.valueOf(previewScrollBar.getValue()));
        previewField.setEditable(false);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        gridBagConstraints.weightx = 0.2;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        jPanel3.add(previewField, gridBagConstraints);

        cytoLabel.setText("Cyto Channel");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        jPanel3.add(cytoLabel, gridBagConstraints);

        sigCanvas.setPreferredSize(new java.awt.Dimension(250, 250));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        jPanel3.add(sigCanvas, gridBagConstraints);

        sigLabel.setText("Sig Channel");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        jPanel3.add(sigLabel, gridBagConstraints);

        previewScrollBar.setOrientation(javax.swing.JScrollBar.HORIZONTAL);
        previewScrollBar.setModel(new DefaultBoundedRangeModel(1, 0, 1, stacks[0].getSize()));
        previewScrollBar.setEnabled(previewToggleButton.isSelected());
        previewScrollBar.addAdjustmentListener(new java.awt.event.AdjustmentListener() {
            public void adjustmentValueChanged(java.awt.event.AdjustmentEvent evt) {
                previewScrollBarAdjustmentValueChanged(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.weightx = 0.8;
        jPanel3.add(previewScrollBar, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.8;
        gridBagConstraints.weighty = 1.0;
        jPanel2.add(jPanel3, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 0.9;
        getContentPane().add(jPanel2, gridBagConstraints);

        jPanel5.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel5.setLayout(new java.awt.GridBagLayout());

        runButton.setText("Run");
        runButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                runButtonActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.insets = new java.awt.Insets(10, 0, 10, 0);
        jPanel5.add(runButton, gridBagConstraints);

        cancelButton.setText("Cancel");
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.insets = new java.awt.Insets(10, 0, 10, 0);
        jPanel5.add(cancelButton, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 0.1;
        getContentPane().add(jPanel5, gridBagConstraints);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
        this.dispose();
        wasOKed = false;
    }//GEN-LAST:event_cancelButtonActionPerformed

    private void runButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_runButtonActionPerformed
        if (!setVariables()) {
            return;
        }
        this.dispose();
        wasOKed = true;
    }//GEN-LAST:event_runButtonActionPerformed

    private void autoThreshToggleButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_autoThreshToggleButtonActionPerformed
        disableFieldOnSelect(greyThreshLabel, greyThreshField, autoThreshToggleButton);
    }//GEN-LAST:event_autoThreshToggleButtonActionPerformed

    private void previewToggleButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_previewToggleButtonActionPerformed
        previewScrollBar.setEnabled(previewToggleButton.isSelected());
        enableFieldOnSelect(null, previewField, previewToggleButton);
        previewScrollBarAdjustmentValueChanged(null);
    }//GEN-LAST:event_previewToggleButtonActionPerformed

    private void anaProtToggleButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_anaProtToggleButtonActionPerformed
        enableFieldOnSelect(minCurveRangeLabel, minCurveRangeField, anaProtToggleButton);
        enableFieldOnSelect(minCurveThreshLabel, minCurveThreshField, anaProtToggleButton);
        enableFieldOnSelect(maxCurveRangeLabel, maxCurveRangeField, anaProtToggleButton);
        enableFieldOnSelect(maxCurveThreshLabel, maxCurveThreshField, anaProtToggleButton);
        enableFieldOnSelect(cutOffLabel, cutOffField, anaProtToggleButton);
        useSigThreshToggleButton.setEnabled(anaProtToggleButton.isSelected());
        useSigThreshToggleButtonActionPerformed(null);
    }//GEN-LAST:event_anaProtToggleButtonActionPerformed

    private void useSigThreshToggleButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_useSigThreshToggleButtonActionPerformed
        enableFieldOnSelect(sigThreshFactLabel, sigThreshFactField, useSigThreshToggleButton);
        enableFieldOnSelect(sigRecThreshLabel, sigRecThreshField, useSigThreshToggleButton);
    }//GEN-LAST:event_useSigThreshToggleButtonActionPerformed

    private void previewScrollBarAdjustmentValueChanged(java.awt.event.AdjustmentEvent evt) {//GEN-FIRST:event_previewScrollBarAdjustmentValueChanged
        if (previewScrollBar.getValueIsAdjusting() || !setVariables()) {
            return;
        }
        ImageProcessor updates[] = analyser.generatePreview(previewScrollBar.getValue());
        ImageProcessor cytoUpdate = checkImageDimensions(updates[0]);
        cytoImp.setProcessor(cytoUpdate);
        cytoCanvas.repaint();
        if (stacks[1] != null) {
            ImageProcessor sigUpdate = checkImageDimensions(updates[1]);
            sigImp.setProcessor(sigUpdate);
            sigCanvas.repaint();
        }
        previewField.setText(String.valueOf(previewScrollBar.getValue()));
    }//GEN-LAST:event_previewScrollBarAdjustmentValueChanged

    private void simpSegRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_simpSegRadioButtonActionPerformed
        advSegRadioButton.setSelected(!simpSegRadioButton.isSelected());
        updateLambdaTextField();
    }//GEN-LAST:event_simpSegRadioButtonActionPerformed

    private void advSegRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_advSegRadioButtonActionPerformed
        simpSegRadioButton.setSelected(!advSegRadioButton.isSelected());
        updateLambdaTextField();
    }//GEN-LAST:event_advSegRadioButtonActionPerformed

    private void velDetectRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_velDetectRadioButtonActionPerformed
        curveDetectRadioButton.setSelected(!velDetectRadioButton.isSelected());
    }//GEN-LAST:event_velDetectRadioButtonActionPerformed

    private void curveDetectRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_curveDetectRadioButtonActionPerformed
        velDetectRadioButton.setSelected(!curveDetectRadioButton.isSelected());
    }//GEN-LAST:event_curveDetectRadioButtonActionPerformed

    private void updateLambdaTextField() {
        lambdaTextField.setEnabled(advSegRadioButton.isSelected());
    }

    private void disableFieldOnSelect(JLabel label, JTextField field, JToggleButton button) {
        field.setEnabled(!(button.isSelected() && button.isEnabled()));
        if (label != null) {
            label.setEnabled(!(button.isSelected() && button.isEnabled()));
        }
    }

    private void enableFieldOnSelect(JLabel label, JTextField field, JToggleButton button) {
        field.setEnabled(button.isSelected() && button.isEnabled());
        if (label != null) {
            label.setEnabled(button.isSelected() && button.isEnabled());
        }
    }

    boolean setVariables() {
        try {
            UserVariables.setGreyThresh(Double.parseDouble(greyThreshField.getText()));
            UserVariables.setGenVis(genVisToggleButton.isSelected());
            UserVariables.setMinCurveRange(Integer.parseInt(minCurveRangeField.getText()));
            UserVariables.setMaxCurveRange(Integer.parseInt(maxCurveRangeField.getText()));
            UserVariables.setUseSigThresh(useSigThreshToggleButton.isSelected());
            UserVariables.setSpatialRes(Double.parseDouble(spatResField.getText()));
            UserVariables.setCutOffTime(Double.parseDouble(cutOffField.getText()));
            UserVariables.setCortexDepth(Double.parseDouble(cortexDepthField.getText()));
            UserVariables.setAutoThreshold(autoThreshToggleButton.isSelected());
            UserVariables.setTempFiltRad(Double.parseDouble(tempFiltRadField.getText()));
            UserVariables.setSigThreshFact(Double.parseDouble(sigThreshFactField.getText()));
            UserVariables.setSpatFiltRad(Double.parseDouble(spatFiltRadField.getText()));
            UserVariables.setErosion(Integer.parseInt(erosionField.getText()));
            UserVariables.setGetMorph(genMorphToggleButton.isSelected());
            UserVariables.setTimeRes(Double.parseDouble(timeResField.getText()));
            UserVariables.setMinCurveThresh(Double.parseDouble(minCurveThreshField.getText()));
            UserVariables.setMaxCurveThresh(Double.parseDouble(maxCurveThreshField.getText()));
            UserVariables.setAnalyseProtrusions(anaProtToggleButton.isSelected());
            UserVariables.setVelDetect(velDetectRadioButton.isSelected());
            UserVariables.setSigRecoveryThresh(Double.parseDouble(sigRecThreshField.getText()));
            UserVariables.setGaussRad(Double.parseDouble(gaussRadField.getText()));
            UserVariables.setSimple(simpSegRadioButton.isSelected());
            UserVariables.setInitGaussRad(Double.parseDouble(initFiltRadTextField.getText()));
            UserVariables.setLambda(Double.parseDouble(lambdaTextField.getText()));
            UserVariables.setMinLength((int) Math.round(Double.parseDouble(minTrajTextField.getText())));
            UserVariables.setThreshMethod(String.valueOf(threshComboBox.getSelectedItem()));
            UserVariables.setBlebDurThresh(Double.parseDouble(protDurTextField.getText()));
            UserVariables.setBlebLenThresh(Double.parseDouble(protLenTextField.getText()));
        } catch (NumberFormatException e) {
            IJ.error("Number formatting error " + e.toString());
            return false;
        }
        return true;
    }

    public boolean isWasOKed() {
        return wasOKed;
    }

    private ImageProcessor checkImageDimensions(ImageProcessor inputImage) {
        ColorProcessor colorImage = (ColorProcessor) (new TypeConverter(inputImage, false)).convertToRGB();
        int width = inputImage.getWidth();
        int height = inputImage.getHeight();
        int pixsize = width * height;
        double widthscale = ((double) width) / MAX_DIM;
        double heightscale = ((double) height) / MAX_DIM;
        if (widthscale > 1.0 || heightscale > 1.0) {
            double scale = 1.0 / Math.max(widthscale, heightscale);
            int scaledwidth = (int) Math.round(scale * colorImage.getWidth());
            byte redPix[] = new byte[pixsize], greenPix[] = new byte[pixsize],
                    bluePix[] = new byte[pixsize];
            colorImage.getRGB(redPix, greenPix, bluePix);
            ImageProcessor red = (new ByteProcessor(width, height, redPix)).resize(scaledwidth);
            ImageProcessor green = (new ByteProcessor(width, height, greenPix)).resize(scaledwidth);
            ImageProcessor blue = (new ByteProcessor(width, height, bluePix)).resize(scaledwidth);
            ColorProcessor output = new ColorProcessor(red.getWidth(), red.getHeight());
            output.setRGB((byte[]) red.getPixels(), (byte[]) green.getPixels(), (byte[]) blue.getPixels());
            return output;
        } else {
            return colorImage;
        }
    }
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the dialog */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                GUI dialog = new GUI(new javax.swing.JFrame(), true);
//                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
//                    @Override
//                    public void windowClosing(java.awt.event.WindowEvent e) {
//                        System.exit(0);
//                    }
//                });
//                dialog.setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton advSegRadioButton;
    private javax.swing.JPanel advancedTab;
    private javax.swing.JToggleButton anaProtToggleButton;
    private javax.swing.JToggleButton autoThreshToggleButton;
    private javax.swing.JButton cancelButton;
    private javax.swing.JTextField cortexDepthField;
    private javax.swing.JLabel cortexDepthLabel;
    private javax.swing.JRadioButton curveDetectRadioButton;
    private javax.swing.JTextField cutOffField;
    private javax.swing.JLabel cutOffLabel;
    private java.awt.Canvas cytoCanvas;
    private javax.swing.JLabel cytoLabel;
    private javax.swing.JTextField erosionField;
    private javax.swing.JLabel erosionLabel;
    private javax.swing.JTextField gaussRadField;
    private javax.swing.JLabel gaussRadLabel;
    private javax.swing.JToggleButton genMorphToggleButton;
    private javax.swing.JToggleButton genVisToggleButton;
    private javax.swing.JTextField greyThreshField;
    private javax.swing.JLabel greyThreshLabel;
    private javax.swing.JLabel initFiltRadLabel;
    private javax.swing.JTextField initFiltRadTextField;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel lambdaLabel;
    private javax.swing.JTextField lambdaTextField;
    private javax.swing.JTextField maxCurveRangeField;
    private javax.swing.JLabel maxCurveRangeLabel;
    private javax.swing.JTextField maxCurveThreshField;
    private javax.swing.JLabel maxCurveThreshLabel;
    private javax.swing.JTextField minCurveRangeField;
    private javax.swing.JLabel minCurveRangeLabel;
    private javax.swing.JTextField minCurveThreshField;
    private javax.swing.JLabel minCurveThreshLabel;
    private javax.swing.JLabel minTrajLabel;
    private javax.swing.JTextField minTrajTextField;
    private javax.swing.JTextField previewField;
    private javax.swing.JScrollBar previewScrollBar;
    private javax.swing.JToggleButton previewToggleButton;
    private javax.swing.JLabel protDurLabel;
    private javax.swing.JTextField protDurTextField;
    private javax.swing.JLabel protLenLabel;
    private javax.swing.JTextField protLenTextField;
    private javax.swing.JButton runButton;
    private java.awt.Canvas sigCanvas;
    private javax.swing.JLabel sigLabel;
    private javax.swing.JTextField sigRecThreshField;
    private javax.swing.JLabel sigRecThreshLabel;
    private javax.swing.JTextField sigThreshFactField;
    private javax.swing.JLabel sigThreshFactLabel;
    private javax.swing.JRadioButton simpSegRadioButton;
    private javax.swing.JPanel simpleTab;
    private javax.swing.JTextField spatFiltRadField;
    private javax.swing.JLabel spatFiltRadLabel;
    private javax.swing.JTextField spatResField;
    private javax.swing.JLabel spatResLabel;
    private javax.swing.JTextField tempFiltRadField;
    private javax.swing.JLabel tempFiltRadLabel;
    private javax.swing.JComboBox threshComboBox;
    private javax.swing.JLabel threshLabel;
    private javax.swing.JTextField timeResField;
    private javax.swing.JLabel timeResLabel;
    private javax.swing.JToggleButton useSigThreshToggleButton;
    private javax.swing.JRadioButton velDetectRadioButton;
    // End of variables declaration//GEN-END:variables
}
